In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import date

In [2]:
mcap_data = pd.read_excel(r"Average Market Capitalization of Listed Companies during Jul - Dec 2020_Final.xlsx")

In [3]:
mcap_data = mcap_data[0:991]

In [4]:
mcap_data = mcap_data.T.reset_index(drop=True).T

In [5]:
mcap_cols = []
for i in range(0,11):
    mcap_cols.append(mcap_data.iloc[0,i])

mcap_cols

['Sr. No.',
 'Company name',
 'ISIN',
 'BSE Symbol',
 'BSE 6 month Avg Total Market Cap in (Rs. Crs.)',
 'NSE Symbol',
 'NSE 6 month Avg Total Market Cap (Rs. Crs.)',
 'MSEI Symbol',
 'MSEI 6 month Avg Total Market Cap in (Rs Crs.)',
 'Average of All Exchanges (Rs. Cr.)',
 'Categorization as per SEBI Circular dated Oct 6, 2017']

In [6]:
mcap_data.columns = mcap_cols

In [7]:
mcap_data.set_index("Sr. No.", inplace = True)
mcap_data.drop(index=['Sr. No.'], inplace= True)

In [8]:
mcap_data

,Company name,ISIN,BSE Symbol,BSE 6 month Avg Total Market Cap in (Rs. Crs.),NSE Symbol,NSE 6 month Avg Total Market Cap (Rs. Crs.),MSEI Symbol,MSEI 6 month Avg Total Market Cap in (Rs Crs.),Average of All Exchanges (Rs. Cr.),"Categorization as per SEBI Circular dated Oct 6, 2017"
Sr. No.,,,,,,,,,,
1,Reliance Industries Ltd,INE002A01018,RELIANCE,1.39318e+06,RELIANCE,1.35638e+06,NaN,NaN,1.37478e+06,Large Cap
2,Tata Consultancy Services Ltd.,INE467B01029,TCS,941811,TCS,941898,NaN,NaN,941854,Large Cap
3,HDFC Bank Ltd.,INE040A01034,HDFCBANK,658577,HDFCBANK,657880,NaN,NaN,658228,Large Cap
4,"Hindustan Unilever Ltd.,",INE030A01027,HINDUNILVR,513598,HINDUNILVR,513591,NaN,NaN,513594,Large Cap
5,Infosys Ltd,INE009A01021,INFY,437657,INFY,437659,NaN,NaN,437658,Large Cap
...,...,...,...,...,...,...,...,...,...,...
986,Mangalore Chemicals & Fertilisers L,INE558B01017,MANGCHEFER,409.06,MANGCHEFER,409.194,NaN,NaN,409.127,Small Cap
987,Ambika Cotton Mills Ltd.,INE540G01014,AMBIKCO,405.83,AMBIKCO,405.835,NaN,NaN,405.832,Small Cap
988,Mishtann Foods Limited,INE094S01041,MISHTANN,404.71,NaN,NaN,MISHTANN,405.941,405.326,Small Cap
989,Stovec Industries Ltd.,INE755D01015,STOVACQ,401.01,NaN,NaN,NaN,NaN,401.01,Small Cap
990,BMW INDUSTRIES LIMITED,INE374E01021,BMW,399.8,NaN,NaN,NaN,NaN,399.8,Small Cap

In [9]:
mcap_data=mcap_data.drop(columns=mcap_data.columns[3:8])

In [10]:
mcap_data.columns = ["Company", "ISIN", "BSE Symbol", "MCap", "Classification"]

In [11]:
mcap_data["Company"]=mcap_data["Company"].str.replace(',', '', regex=True)
mcap_data

,Company,ISIN,BSE Symbol,MCap,Classification
Sr. No.,,,,,
1,Reliance Industries Ltd,INE002A01018,RELIANCE,1.37478e+06,Large Cap
2,Tata Consultancy Services Ltd.,INE467B01029,TCS,941854,Large Cap
3,HDFC Bank Ltd.,INE040A01034,HDFCBANK,658228,Large Cap
4,Hindustan Unilever Ltd.,INE030A01027,HINDUNILVR,513594,Large Cap
5,Infosys Ltd,INE009A01021,INFY,437658,Large Cap
...,...,...,...,...,...
986,Mangalore Chemicals & Fertilisers L,INE558B01017,MANGCHEFER,409.127,Small Cap
987,Ambika Cotton Mills Ltd.,INE540G01014,AMBIKCO,405.832,Small Cap
988,Mishtann Foods Limited,INE094S01041,MISHTANN,405.326,Small Cap
989,Stovec Industries Ltd.,INE755D01015,STOVACQ,401.01,Small Cap
990,BMW INDUSTRIES LIMITED,INE374E01021,BMW,399.8,Small Cap

In [12]:
mcap_data['Size']= mcap_data['MCap']
for i in range(1,len(mcap_data['MCap'])+1):
    mcap_data['Size'].loc[i] = -np.log(mcap_data["MCap"].loc[i])

In [13]:
y = mcap_data['Size']
outliers_downside = y.between(y.quantile(0), y.quantile(.05))
outliers_upside = y.between(y.quantile(0.95), y.quantile(1))

#removed_outliers = y.between(y.quantile(.05), y.quantile(.95))
fifth_percentile_mcap = y.quantile(.05)
nintyfifth_percentile_mcap = y.quantile(.95)

In [14]:
outliers_downside_index = mcap_data[outliers_downside].index
outliers_upside_index = mcap_data[outliers_upside].index

In [15]:
fifth_percentile_mcap, nintyfifth_percentile_mcap

(-11.00117299460302, -6.152756491561248)

In [16]:
for ind in outliers_downside_index:
    mcap_data.loc[ind]["Size"] = fifth_percentile_mcap
    
for ind in outliers_upside_index:
    mcap_data.loc[ind]["Size"] = nintyfifth_percentile_mcap

In [17]:
min(mcap_data["Size"]), max(mcap_data["Size"])

(-11.00117299460302, -6.152756491561248)

In [18]:
mcap_data["Size Z Score"] = (mcap_data["Size"] - mcap_data["Size"].mean())/mcap_data["Size"].std(ddof=0)

In [19]:
mcap_data

,Company,ISIN,BSE Symbol,MCap,Classification,Size,Size Z Score
Sr. No.,,,,,,,
1,Reliance Industries Ltd,INE002A01018,RELIANCE,1.37478e+06,Large Cap,-11.0012,-2.04303
2,Tata Consultancy Services Ltd.,INE467B01029,TCS,941854,Large Cap,-11.0012,-2.04303
3,HDFC Bank Ltd.,INE040A01034,HDFCBANK,658228,Large Cap,-11.0012,-2.04303
4,Hindustan Unilever Ltd.,INE030A01027,HINDUNILVR,513594,Large Cap,-11.0012,-2.04303
5,Infosys Ltd,INE009A01021,INFY,437658,Large Cap,-11.0012,-2.04303
...,...,...,...,...,...,...,...
986,Mangalore Chemicals & Fertilisers L,INE558B01017,MANGCHEFER,409.127,Small Cap,-6.15276,1.26526
987,Ambika Cotton Mills Ltd.,INE540G01014,AMBIKCO,405.832,Small Cap,-6.15276,1.26526
988,Mishtann Foods Limited,INE094S01041,MISHTANN,405.326,Small Cap,-6.15276,1.26526
989,Stovec Industries Ltd.,INE755D01015,STOVACQ,401.01,Small Cap,-6.15276,1.26526
990,BMW INDUSTRIES LIMITED,INE374E01021,BMW,399.8,Small Cap,-6.15276,1.26526

In [20]:
size_score = []
for i in range(len(mcap_data)):
    if mcap_data.iloc[i]["Size Z Score"] > 0:
        size_score.append(1 + mcap_data.iloc[i]["Size Z Score"])
    elif mcap_data.iloc[i]["Size Z Score"] < 0:
        size_score.append((1 - mcap_data.iloc[i]["Size Z Score"])**(-1))

In [21]:
mcap_data["Size Score"] = size_score
mcap_data["Size Rank"] = mcap_data["Size Score"].rank(ascending = False)

In [22]:
mcap_data.sort_values(by = ["Size Rank"])

,Company,ISIN,BSE Symbol,MCap,Classification,Size,Size Z Score,Size Score,Size Rank
Sr. No.,,,,,,,,,
990,BMW INDUSTRIES LIMITED,INE374E01021,BMW,399.8,Small Cap,-6.15276,1.26526,2.265257,25.5
962,Unitech Ltd.,INE694A01020,UNITECH,444.089,Small Cap,-6.15276,1.26526,2.265257,25.5
961,WPIL Ltd,INE765D01014,WPIL,444.15,Small Cap,-6.15276,1.26526,2.265257,25.5
960,Pokarna Ltd.,INE637C01025,POKARNA,445.1,Small Cap,-6.15276,1.26526,2.265257,25.5
959,Dynamatic Technologies Ltd.,INE221B01012,DYNAMATECH,445.36,Small Cap,-6.15276,1.26526,2.265257,25.5
...,...,...,...,...,...,...,...,...,...
31,Britannia Industries Ltd.,INE216A01030,BRITANNIA,88924.6,Large Cap,-11.0012,-2.04303,0.328620,965.5
29,Hindustan Zinc Ltd.,INE267A01025,HINDZINC,92855.9,Large Cap,-11.0012,-2.04303,0.328620,965.5
28,POWER GRID CORPORATION OF INDIA LIMITED,INE752E01010,POWERGRID,93038.3,Large Cap,-11.0012,-2.04303,0.328620,965.5
39,Coal India Limited,INE522F01014,COALINDIA,78845.4,Large Cap,-11.0012,-2.04303,0.328620,965.5
1,Reliance Industries Ltd,INE002A01018,RELIANCE,1.37478e+06,Large Cap,-11.0012,-2.04303,0.328620,965.5

In [113]:
mcap_data[mcap_data["Company"]=="Coal India Limited"]

,Company,MCap,Classification,Size,Size Z Score,Size Score,Size Rank
Sr. No.,,,,,,,
39,Coal India Limited,78845.4,Large Cap,-11.0012,-2.04303,0.32862,965.5